using System.Collections.Generic;

namespace NexusLabs.Needlr.Copilot;

/// <summary>
/// The structured result of a Copilot web search, including the answer text,
/// source citations, and the search queries that were performed.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="ToString"/> returns <see cref="Text"/> so that existing agent
/// tool flows (which stringify tool results) continue to work unchanged.
/// </para>
/// <para>
/// Host code that needs citation or search query metadata can inspect
/// <see cref="Citations"/> and <see cref="SearchQueries"/> directly.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var tools = CopilotToolSet.Create(opts => opts.EnableWebSearch = true);
/// var webSearch = tools[0];
/// var result = await webSearch.InvokeAsync(new AIFunctionArguments(
///     new Dictionary&lt;string, object?&gt; { ["query"] = "latest .NET version" }));
///
/// if (result is WebSearchResult searchResult)
/// {
///     Console.WriteLine(searchResult.Text);
///     foreach (var citation in searchResult.Citations)
///     {
///         Console.WriteLine($"  [{citation.Title}]({citation.Url})");
///     }
/// }
/// </code>
/// </example>
public sealed class WebSearchResult
{
    internal WebSearchResult(
        string text,
        IReadOnlyList<WebSearchCitation> citations,
        IReadOnlyList<WebSearchQuery> searchQueries)
    {
        Text = text;
        Citations = citations;
        SearchQueries = searchQueries;
    }

    /// <summary>
    /// The answer text generated by the web search. May contain
    /// <c>【3:N†source】</c> citation markers whose positions are
    /// described by <see cref="Citations"/>.
    /// </summary>
    public string Text { get; }

    /// <summary>
    /// Source citations extracted from the search result. Each citation maps a
    /// character span in <see cref="Text"/> to a source URL. Empty when the
    /// API did not return any annotations.
    /// </summary>
    public IReadOnlyList<WebSearchCitation> Citations { get; }

    /// <summary>
    /// The Bing search queries that the Copilot web search tool performed
    /// while generating the answer. Empty when no web searches were triggered.
    /// </summary>
    public IReadOnlyList<WebSearchQuery> SearchQueries { get; }

    /// <summary>
    /// Returns <see cref="Text"/> so that agent tool flows that stringify
    /// results continue to receive the answer content.
    /// </summary>
    public override string ToString() => Text;
}
