namespace NexusLabs.Needlr.AgentFramework.Langfuse;

/// <summary>
/// Declares the shape of a named Langfuse score so the dashboard renders consistent ranges,
/// colors, and category sets and validates incoming values. Created via
/// <see cref="ILangfuseScoreConfigClient.EnsureScoreConfigAsync"/>.
/// </summary>
/// <remarks>
/// Score configs are project-level setup, typically ensured once at the start of an eval suite.
/// They are matched to scores by <see cref="Name"/>, so use the same name you pass when recording
/// the score (and the same casing/normalization).
/// </remarks>
public sealed record LangfuseScoreConfig
{
    /// <summary>
    /// Gets the score config name (max 35 characters; letters, numbers, underscores, spaces,
    /// periods, parentheses, and hyphens). Must match the score name used when recording.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>Gets the data type the score values must conform to.</summary>
    public required LangfuseScoreDataType DataType { get; init; }

    /// <summary>
    /// Gets the inclusive minimum for <see cref="LangfuseScoreDataType.Numeric"/> scores. Ignored
    /// for other data types. <see langword="null"/> leaves the minimum unbounded.
    /// </summary>
    public double? MinValue { get; init; }

    /// <summary>
    /// Gets the inclusive maximum for <see cref="LangfuseScoreDataType.Numeric"/> scores. Ignored
    /// for other data types. <see langword="null"/> leaves the maximum unbounded.
    /// </summary>
    public double? MaxValue { get; init; }

    /// <summary>
    /// Gets the allowed categories for a <see cref="LangfuseScoreDataType.Categorical"/> score.
    /// Required for categorical configs; must be omitted for other data types (boolean categories
    /// are generated by Langfuse).
    /// </summary>
    public IReadOnlyList<LangfuseScoreConfigCategory>? Categories { get; init; }

    /// <summary>Gets an optional description shown across the Langfuse UI.</summary>
    public string? Description { get; init; }
}
