using Azure;
using Azure.AI.OpenAI;

using Microsoft.Extensions.AI;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

using NexusLabs.Needlr.AgentFramework;
using NexusLabs.Needlr.AgentFramework.Workflows;
using NexusLabs.Needlr.Injection;
using NexusLabs.Needlr.Injection.Reflection;

// Generated extension methods: CreateCodeReviewGroupChatWorkflow() on IWorkflowFactory.
// These are emitted by the source generator in GroupChatAgentFrameworkApp.Agents based on
// [AgentGroupChatMember("code-review")] attributes declared on the three reviewer agents.
using GroupChatAgentFrameworkApp.Agents.Generated;

var configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json", optional: true)
    .AddJsonFile("appsettings.Development.json", optional: true)
    .AddEnvironmentVariables()
    .Build();

var azureSection = configuration.GetSection("AzureOpenAI");
IChatClient chatClient = new AzureOpenAIClient(
        new Uri(azureSection["Endpoint"]
            ?? throw new InvalidOperationException("No AzureOpenAI:Endpoint set")),
        new AzureKeyCredential(azureSection["ApiKey"]
            ?? throw new InvalidOperationException("No AzureOpenAI:ApiKey set")))
    .GetChatClient(azureSection["DeploymentName"]
        ?? throw new InvalidOperationException("No AzureOpenAI:DeploymentName set"))
    .AsIChatClient();

// The [ModuleInitializer] emitted by the source generator in GroupChatAgentFrameworkApp.Agents
// fires on assembly load and registers all [NeedlrAiAgent] types and their [AgentGroupChatMember]
// group memberships with AgentFrameworkGeneratedBootstrap. No explicit Add* calls needed.
var serviceProvider = new Syringe()
    .UsingReflection()
    .UsingAssemblyProvider(b => b.MatchingAssemblies(path =>
        path.Contains("GroupChatAgentFrameworkApp", StringComparison.OrdinalIgnoreCase)).Build())
    .UsingAgentFramework(af => af.UsingChatClient(chatClient))
    .BuildServiceProvider(configuration);

// IWorkflowFactory reads group membership declared via [AgentGroupChatMember] on agent classes.
// No agent type references or workflow builder calls needed in the composition root.
var workflowFactory = serviceProvider.GetRequiredService<IWorkflowFactory>();

// CreateCodeReviewGroupChatWorkflow() is generated by the source generator because
// SecurityReviewerAgent, PerformanceReviewerAgent, and StyleReviewerAgent are all decorated
// with [AgentGroupChatMember("code-review")].
// Adding a new reviewer agent requires only adding the attribute — this line never changes.
var workflow = workflowFactory.CreateCodeReviewGroupChatWorkflow(maxIterations: 2);

Console.WriteLine("=== Needlr + MAF: Round-Robin Group Chat Code Review ===");
Console.WriteLine("  Group membership declared via [AgentGroupChatMember] on each reviewer.");
Console.WriteLine("  ReviewOrchestratorAgent carries [AgentTerminationCondition] — the workflow");
Console.WriteLine("  stops as soon as it outputs CONSENSUS: APPROVED or CONSENSUS: CHANGES REQUIRED.");
Console.WriteLine();

// A deliberately flawed code snippet to review — has security, performance, and style issues.
const string codeToReview = """
    public List<User> GetUsers(string role)
    {
        var users = new List<User>();
        var conn = new SqlConnection("Server=prod;Database=app;User=sa;Password=P@ss123");
        conn.Open();
        var cmd = new SqlCommand("SELECT * FROM Users WHERE Role = '" + role + "'", conn);
        var reader = cmd.ExecuteReader();
        while (reader.Read())
        {
            var u = new User();
            u.Id = (int)reader["Id"];
            u.Name = (string)reader["Name"];
            u.Role = (string)reader["Role"];
            users.Add(u);
        }
        return users;
    }
    """;

Console.WriteLine("Code under review:");
Console.WriteLine(codeToReview);
Console.WriteLine();
Console.WriteLine("--- Review panel responses ---");
Console.WriteLine();

var responses = await workflow.RunAsync(
    $"Please review this code:\n\n```csharp\n{codeToReview}\n```");

foreach (var (executorId, text) in responses)
{
    Console.WriteLine($"[{executorId}]");
    Console.WriteLine(text.Trim());
    Console.WriteLine();
}
