// Copyright (c) NexusLabs. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NexusLabs.Needlr.AgentFramework.Generators;

internal static class AIFunctionProviderCodeGenerator
{
    public static string GenerateAIFunctionProviderSource(
        List<AgentFunctionTypeInfo> types,
        string safeAssemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
        sb.AppendLine("internal sealed class GeneratedAIFunctionProvider : global::NexusLabs.Needlr.AgentFramework.IAIFunctionProvider");
        sb.AppendLine("{");
        sb.AppendLine("    public bool TryGetFunctions(");
        sb.AppendLine("        global::System.Type functionType,");
        sb.AppendLine("        global::System.IServiceProvider serviceProvider,");
        sb.AppendLine("        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]");
        sb.AppendLine("        out global::System.Collections.Generic.IReadOnlyList<global::Microsoft.Extensions.AI.AIFunction>? functions)");
        sb.AppendLine("    {");

        if (types.Count == 0)
        {
            sb.AppendLine("        functions = null;");
            sb.AppendLine("        return false;");
        }
        else
        {
            var first = true;
            foreach (var type in types)
            {
                var keyword = first ? "if" : "else if";
                first = false;
                sb.AppendLine($"        {keyword} (functionType == typeof({type.TypeName}))");
                sb.AppendLine("        {");
                if (!type.IsStatic)
                    sb.AppendLine($"            var typed = serviceProvider.GetRequiredService<{type.TypeName}>();");
                sb.AppendLine("            functions = new global::System.Collections.Generic.List<global::Microsoft.Extensions.AI.AIFunction>");
                sb.AppendLine("            {");
                foreach (var m in type.Methods)
                {
                    var nestedName = $"{AgentDiscoveryHelper.GetShortName(type.TypeName)}_{m.MethodName}";
                    if (type.IsStatic)
                        sb.AppendLine($"                new {nestedName}(),");
                    else
                        sb.AppendLine($"                new {nestedName}(typed),");
                }
                sb.AppendLine("            }.AsReadOnly();");
                sb.AppendLine("            return true;");
                sb.AppendLine("        }");
            }
            sb.AppendLine("        functions = null;");
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var type in types)
        {
            var shortTypeName = AgentDiscoveryHelper.GetShortName(type.TypeName);
            foreach (var m in type.Methods)
            {
                var nestedName = $"{shortTypeName}_{m.MethodName}";
                AppendAIFunctionNestedClass(sb, type, m, nestedName);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendAIFunctionNestedClass(
        StringBuilder sb,
        AgentFunctionTypeInfo type,
        AgentFunctionMethodInfo method,
        string nestedClassName)
    {
        sb.AppendLine($"    private sealed class {nestedClassName} : global::Microsoft.Extensions.AI.AIFunction");
        sb.AppendLine("    {");

        if (!type.IsStatic)
            sb.AppendLine($"        private readonly {type.TypeName} _instance;");

        var schemaJson = BuildJsonSchema(method.Parameters);
        sb.AppendLine("        private static readonly global::System.Text.Json.JsonElement _schema =");
        sb.AppendLine($"            global::System.Text.Json.JsonDocument.Parse(\"\"\"{schemaJson}\"\"\").RootElement.Clone();");

        if (!string.IsNullOrEmpty(method.ReturnJsonSchemaType))
        {
            var returnSchemaJson = !string.IsNullOrEmpty(method.ReturnObjectSchemaJson)
                ? method.ReturnObjectSchemaJson
                : $"{{\"type\":\"{method.ReturnJsonSchemaType}\"}}";
            sb.AppendLine("        private static readonly global::System.Text.Json.JsonElement _returnSchema =");
            sb.AppendLine($"            global::System.Text.Json.JsonDocument.Parse(\"\"\"{returnSchemaJson}\"\"\").RootElement.Clone();");
        }

        sb.AppendLine();

        if (!type.IsStatic)
            sb.AppendLine($"        public {nestedClassName}({type.TypeName} instance) {{ _instance = instance; }}");
        else
            sb.AppendLine($"        public {nestedClassName}() {{ }}");

        sb.AppendLine();

        var escapedName = method.MethodName.Replace("\"", "\\\"");
        var escapedDesc = method.Description.Replace("\\", "\\\\").Replace("\"", "\\\"");
        sb.AppendLine($"        public override string Name => \"{escapedName}\";");
        sb.AppendLine($"        public override string Description => \"{escapedDesc}\";");
        sb.AppendLine("        public override global::System.Text.Json.JsonElement JsonSchema => _schema;");

        if (!string.IsNullOrEmpty(method.ReturnJsonSchemaType))
        {
            sb.AppendLine("        public override global::System.Text.Json.JsonElement? ReturnJsonSchema => _returnSchema;");
        }

        sb.AppendLine();

        if (method.IsAsync)
            sb.AppendLine("        protected override async global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(");
        else
            sb.AppendLine("        protected override global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(");

        sb.AppendLine("            global::Microsoft.Extensions.AI.AIFunctionArguments arguments,");
        sb.AppendLine("            global::System.Threading.CancellationToken ct)");
        sb.AppendLine("        {");

        foreach (var param in method.Parameters)
        {
            if (param.IsCancellationToken)
                continue;
            AppendParameterExtraction(sb, param);
        }

        var paramList = string.Join(", ", method.Parameters.Select(p => p.IsCancellationToken ? "ct" : p.Name));
        var instanceExpr = type.IsStatic ? type.TypeName : "_instance";

        if (method.IsAsync)
        {
            if (method.IsVoidLike)
            {
                sb.AppendLine($"            await {instanceExpr}.{method.MethodName}({paramList}).ConfigureAwait(false);");
                sb.AppendLine("            return null;");
            }
            else
            {
                sb.AppendLine($"            var result = await {instanceExpr}.{method.MethodName}({paramList}).ConfigureAwait(false);");
                sb.AppendLine("            return result;");
            }
        }
        else
        {
            if (method.IsVoidLike)
            {
                sb.AppendLine($"            {instanceExpr}.{method.MethodName}({paramList});");
                sb.AppendLine("            return global::System.Threading.Tasks.ValueTask.FromResult<object?>(null);");
            }
            else
            {
                sb.AppendLine($"            var result = {instanceExpr}.{method.MethodName}({paramList});");
                sb.AppendLine("            return global::System.Threading.Tasks.ValueTask.FromResult<object?>(result);");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string BuildJsonSchema(ImmutableArray<AgentFunctionParameterInfo> parameters)
    {
        var nonCtParams = parameters.Where(p => !p.IsCancellationToken).ToList();
        if (nonCtParams.Count == 0)
            return "{\"type\":\"object\",\"properties\":{}}";

        var props = new StringBuilder();
        var required = new List<string>();

        props.Append("{");
        var firstProp = true;
        foreach (var param in nonCtParams)
        {
            if (!firstProp) props.Append(",");
            firstProp = false;
            var escapedParamName = param.Name.Replace("\"", "\\\"");
            props.Append($"\"{escapedParamName}\":");
            props.Append(BuildJsonSchemaTypeEntry(param));
            if (param.IsRequired)
                required.Add(param.Name);
        }
        props.Append("}");

        var sb = new StringBuilder();
        sb.Append("{\"type\":\"object\",\"properties\":");
        sb.Append(props);
        if (required.Count > 0)
        {
            sb.Append(",\"required\":[");
            sb.Append(string.Join(",", required.Select(r => "\"" + r.Replace("\"", "\\\"") + "\"")));
            sb.Append("]");
        }
        sb.Append("}");
        return sb.ToString();
    }

    private static string BuildJsonSchemaTypeEntry(AgentFunctionParameterInfo param)
    {
        if (string.IsNullOrEmpty(param.JsonSchemaType))
            return "{}";

        if (param.JsonSchemaType == "array")
        {
            var desc = string.IsNullOrEmpty(param.Description)
                ? ""
                : $",\"description\":\"{param.Description!.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

            if (param.ItemJsonSchemaType == "object" && !string.IsNullOrEmpty(param.ItemObjectSchemaJson))
            {
                // Complex object array items — emit the full object schema
                return $"{{\"type\":\"array\",\"items\":{param.ItemObjectSchemaJson}{desc}}}";
            }

            if (!string.IsNullOrEmpty(param.ItemJsonSchemaType))
                return $"{{\"type\":\"array\",\"items\":{{\"type\":\"{param.ItemJsonSchemaType}\"}}{desc}}}";

            return $"{{\"type\":\"array\"{desc}}}";
        }

        if (param.JsonSchemaType == "object")
        {
            // Direct complex object parameter (not in an array)
            var desc = string.IsNullOrEmpty(param.Description)
                ? ""
                : $",\"description\":\"{param.Description!.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
            return $"{{\"type\":\"object\"{desc}}}";
        }

        if (!string.IsNullOrEmpty(param.Description))
        {
            var escapedDesc = param.Description!.Replace("\\", "\\\\").Replace("\"", "\\\"");
            return $"{{\"type\":\"{param.JsonSchemaType}\",\"description\":\"{escapedDesc}\"}}";
        }

        return $"{{\"type\":\"{param.JsonSchemaType}\"}}";
    }

    private const string ExtractorFqn = "global::NexusLabs.Needlr.AgentFramework.AgentFrameworkArgumentExtractor";

    private static void AppendParameterExtraction(StringBuilder sb, AgentFunctionParameterInfo param)
    {
        var rawVar = $"_raw_{param.Name}";
        var jVar = $"_j_{param.Name}";
        sb.AppendLine($"            arguments.TryGetValue(\"{param.Name}\", out var {rawVar});");

        switch (param.JsonSchemaType)
        {
            case "string":
                sb.AppendLine($"            var {param.Name} = {ExtractorFqn}.GetStringArgument({rawVar});");
                break;
            case "boolean":
                sb.AppendLine($"            var {param.Name} = {ExtractorFqn}.GetBooleanArgument({rawVar});");
                break;
            case "integer":
                AppendIntegerExtraction(sb, param, rawVar);
                break;
            case "number":
                AppendNumberExtraction(sb, param, rawVar);
                break;
            case "array":
            {
                // AOT-safe array extraction: manually enumerate JsonElement items
                // instead of using JsonSerializer.Deserialize<T[]> (which triggers
                // IL2026/IL3050 in NativeAOT builds).
                var elementType = GetArrayElementType(param.TypeFullName);
                sb.AppendLine($"            {param.TypeFullName} {param.Name};");
                sb.AppendLine($"            if ({rawVar} is global::System.Text.Json.JsonElement {jVar} && {jVar}.ValueKind == global::System.Text.Json.JsonValueKind.Array)");
                sb.AppendLine("            {");
                sb.AppendLine($"                var _list_{param.Name} = new global::System.Collections.Generic.List<{elementType}>();");
                sb.AppendLine($"                foreach (var _elem in {jVar}.EnumerateArray())");
                sb.AppendLine("                {");

                if (param.ItemJsonSchemaType == "object" && param.ItemObjectProperties is { Count: > 0 })
                {
                    // Complex object: manual property extraction (AOT-safe). Each
                    // property goes through the kind-tolerant helper so a
                    // model-supplied numeric stays parseable as int via String
                    // path, an array literal becomes canonical JSON for a string
                    // property, etc.
                    sb.AppendLine($"                    var _obj = new {elementType}();");
                    foreach (var prop in param.ItemObjectProperties)
                    {
                        sb.AppendLine($"                    if (_elem.TryGetProperty(\"{prop.JsonName}\", out var _p_{prop.JsonName}))");
                        switch (prop.SchemaType)
                        {
                            case "string":
                                sb.AppendLine($"                        _obj.{prop.CSharpName} = {ExtractorFqn}.GetStringArgument(_p_{prop.JsonName});");
                                break;
                            case "integer":
                                sb.AppendLine($"                        _obj.{prop.CSharpName} = {ExtractorFqn}.GetInt32Argument(_p_{prop.JsonName});");
                                break;
                            case "number":
                                sb.AppendLine($"                        _obj.{prop.CSharpName} = {ExtractorFqn}.GetDoubleArgument(_p_{prop.JsonName});");
                                break;
                            case "boolean":
                                sb.AppendLine($"                        _obj.{prop.CSharpName} = {ExtractorFqn}.GetBooleanArgument(_p_{prop.JsonName});");
                                break;
                            default:
                                sb.AppendLine($"                        _obj.{prop.CSharpName} = {ExtractorFqn}.GetStringArgument(_p_{prop.JsonName});");
                                break;
                        }
                    }
                    sb.AppendLine($"                    _list_{param.Name}.Add(_obj);");
                }
                else if (param.ItemJsonSchemaType == "string")
                    sb.AppendLine($"                    _list_{param.Name}.Add({ExtractorFqn}.GetStringArgument(_elem));");
                else if (param.ItemJsonSchemaType == "integer")
                    sb.AppendLine($"                    _list_{param.Name}.Add({ExtractorFqn}.GetInt32Argument(_elem));");
                else if (param.ItemJsonSchemaType == "number")
                    sb.AppendLine($"                    _list_{param.Name}.Add({ExtractorFqn}.GetDoubleArgument(_elem));");
                else if (param.ItemJsonSchemaType == "boolean")
                    sb.AppendLine($"                    _list_{param.Name}.Add({ExtractorFqn}.GetBooleanArgument(_elem));");
                else
                    sb.AppendLine($"                    _list_{param.Name}.Add(default!);");

                sb.AppendLine("                }");
                sb.AppendLine($"                {param.Name} = _list_{param.Name}.ToArray();");
                sb.AppendLine("            }");
                sb.AppendLine($"            else {{ {param.Name} = {rawVar} as {param.TypeFullName} ?? global::System.Array.Empty<{elementType}>(); }}");
                break;
            }
            case "object":
            {
                var cVar = $"_c_{param.Name}";
                var nullSuppress = param.IsNullable ? "" : "!";
                sb.AppendLine($"            var {param.Name} = {rawVar} is {param.TypeFullName} {cVar} ? {cVar} : default({param.TypeFullName}){nullSuppress};");
                break;
            }
            default:
            {
                var cVar = $"_c_{param.Name}";
                var nullSuppress = param.IsNullable ? "" : "!";
                sb.AppendLine($"            var {param.Name} = {rawVar} is {param.TypeFullName} {cVar} ? {cVar} : default({param.TypeFullName}){nullSuppress};");
                break;
            }
        }
    }

    private static void AppendIntegerExtraction(StringBuilder sb, AgentFunctionParameterInfo param, string rawVar)
    {
        var typeFqn = param.TypeFullName;
        string helperMethod;

        if (typeFqn.Contains("System.Int64"))
            helperMethod = "GetInt64Argument";
        else if (typeFqn.Contains("System.Int16"))
            helperMethod = "GetInt16Argument";
        else if (typeFqn.Contains("System.SByte"))
            helperMethod = "GetSByteArgument";
        else if (typeFqn.Contains("System.Byte"))
            helperMethod = "GetByteArgument";
        else if (typeFqn.Contains("System.UInt64"))
            helperMethod = "GetUInt64Argument";
        else if (typeFqn.Contains("System.UInt32"))
            helperMethod = "GetUInt32Argument";
        else if (typeFqn.Contains("System.UInt16"))
            helperMethod = "GetUInt16Argument";
        else
            helperMethod = "GetInt32Argument";

        sb.AppendLine($"            var {param.Name} = {ExtractorFqn}.{helperMethod}({rawVar});");
    }

    private static void AppendNumberExtraction(StringBuilder sb, AgentFunctionParameterInfo param, string rawVar)
    {
        var typeFqn = param.TypeFullName;
        string helperMethod;

        if (typeFqn.Contains("System.Single"))
            helperMethod = "GetSingleArgument";
        else if (typeFqn.Contains("System.Decimal"))
            helperMethod = "GetDecimalArgument";
        else
            helperMethod = "GetDoubleArgument";

        sb.AppendLine($"            var {param.Name} = {ExtractorFqn}.{helperMethod}({rawVar});");
    }

    /// <summary>
    /// Extracts the element type from an array type's fully-qualified name.
    /// E.g., <c>"global::MyNamespace.FeedbackEntry[]"</c> → <c>"global::MyNamespace.FeedbackEntry"</c>.
    /// </summary>
    private static string GetArrayElementType(string arrayTypeFullName)
    {
        // Handle T[] syntax
        if (arrayTypeFullName.EndsWith("[]"))
            return arrayTypeFullName.Substring(0, arrayTypeFullName.Length - 2);

        // Fallback: return as-is (shouldn't happen for valid array types)
        return arrayTypeFullName;
    }
}
