using System.Text;

using NexusLabs.Needlr.AgentFramework.Generators.Models;

namespace NexusLabs.Needlr.AgentFramework.Generators.CodeGen
{
    internal static class AsyncLocalScopedCodeGenerator
    {
        public static string Generate(AsyncLocalScopedInfo info)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// AsyncLocal-backed implementation for " + info.InterfaceName);
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(info.NamespaceName))
            {
                sb.AppendLine("namespace " + info.NamespaceName);
                sb.AppendLine("{");
            }

            sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
            sb.AppendLine("internal sealed class " + info.GeneratedClassName + " : " + info.InterfaceFullName);
            sb.AppendLine("{");

            if (info.IsMutable)
            {
                GenerateMutablePattern(sb, info);
            }
            else
            {
                GenerateSimplePattern(sb, info);
            }

            sb.AppendLine("}");

            if (!string.IsNullOrEmpty(info.NamespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void GenerateSimplePattern(StringBuilder sb, AsyncLocalScopedInfo info)
        {
            var valueType = info.ValueTypeFullName;

            sb.AppendLine("    private static readonly global::System.Threading.AsyncLocal<" + valueType + "?> _current = new global::System.Threading.AsyncLocal<" + valueType + "?>();");
            sb.AppendLine();
            sb.AppendLine("    public " + valueType + "? Current => _current.Value;");
            sb.AppendLine();

            GeneratePropertyProxies(sb, info, "_current.Value");

            if (info.HasScopeParameter)
            {
                sb.AppendLine("    public global::System.IDisposable " + info.ScopeMethodName + "(" + info.ScopeParameterTypeFullName + " value)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (value == null) throw new global::System.ArgumentNullException(nameof(value));");
                sb.AppendLine();
                sb.AppendLine("        var previous = _current.Value;");
                sb.AppendLine("        _current.Value = value;");
                sb.AppendLine("        return new Scope(previous);");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine("    public global::System.IDisposable " + info.ScopeMethodName + "()");
                sb.AppendLine("    {");
                sb.AppendLine("        var previous = _current.Value;");
                sb.AppendLine("        _current.Value = default;");
                sb.AppendLine("        return new Scope(previous);");
                sb.AppendLine("    }");
            }

            sb.AppendLine();
            sb.AppendLine("    private sealed class Scope : global::System.IDisposable");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly " + valueType + "? _previous;");
            sb.AppendLine("        private bool _disposed;");
            sb.AppendLine();
            sb.AppendLine("        public Scope(" + valueType + "? previous) => _previous = previous;");
            sb.AppendLine();
            sb.AppendLine("        public void Dispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_disposed) return;");
            sb.AppendLine("            _disposed = true;");
            sb.AppendLine("            _current.Value = _previous;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static void GenerateMutablePattern(StringBuilder sb, AsyncLocalScopedInfo info)
        {
            var valueType = info.ValueTypeFullName;

            sb.AppendLine("    private static readonly global::System.Threading.AsyncLocal<Holder?> _current = new global::System.Threading.AsyncLocal<Holder?>();");
            sb.AppendLine();
            sb.AppendLine("    public " + valueType + "? Current => _current.Value?.Value;");
            sb.AppendLine();

            GeneratePropertyProxies(sb, info, "_current.Value?.Value");

            if (info.HasScopeParameter)
            {
                sb.AppendLine("    public global::System.IDisposable " + info.ScopeMethodName + "(" + info.ScopeParameterTypeFullName + " value)");
                sb.AppendLine("    {");
                sb.AppendLine("        var previous = _current.Value;");
                sb.AppendLine("        _current.Value = new Holder() { Value = value };");
                sb.AppendLine("        return new Scope(previous);");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine("    public global::System.IDisposable " + info.ScopeMethodName + "()");
                sb.AppendLine("    {");
                sb.AppendLine("        var previous = _current.Value;");
                sb.AppendLine("        _current.Value = new Holder();");
                sb.AppendLine("        return new Scope(previous);");
                sb.AppendLine("    }");
            }

            sb.AppendLine();
            sb.AppendLine("    internal void Set(" + valueType + " value)");
            sb.AppendLine("    {");
            sb.AppendLine("        var holder = _current.Value;");
            sb.AppendLine("        if (holder != null)");
            sb.AppendLine("        {");
            sb.AppendLine("            holder.Value = value;");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            _current.Value = new Holder() { Value = value };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private sealed class Holder");
            sb.AppendLine("    {");
            sb.AppendLine("        public " + valueType + "? Value;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private sealed class Scope : global::System.IDisposable");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly Holder? _previous;");
            sb.AppendLine("        private bool _disposed;");
            sb.AppendLine();
            sb.AppendLine("        public Scope(Holder? previous) => _previous = previous;");
            sb.AppendLine();
            sb.AppendLine("        public void Dispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_disposed) return;");
            sb.AppendLine("            _disposed = true;");
            sb.AppendLine("            _current.Value = _previous;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static void GeneratePropertyProxies(
            StringBuilder sb,
            AsyncLocalScopedInfo info,
            string currentExpression)
        {
            if (info.ProxyProperties.Length == 0)
                return;

            foreach (var prop in info.ProxyProperties)
            {
                var getExpr = currentExpression + "?." + prop.Name;
                if (prop.IsNonNullableValueType)
                {
                    getExpr += " ?? default";
                }

                if (prop.HasSetter)
                {
                    sb.AppendLine("    public " + prop.TypeFullName + " " + prop.Name);
                    sb.AppendLine("    {");
                    sb.AppendLine("        get => " + getExpr + ";");
                    sb.AppendLine("        set { if (" + currentExpression + " is { } h) h." + prop.Name + " = value; }");
                    sb.AppendLine("    }");
                }
                else
                {
                    sb.AppendLine("    public " + prop.TypeFullName + " " + prop.Name + " => " + getExpr + ";");
                }

                sb.AppendLine();
            }
        }
    }
}
