// Copyright (c) NexusLabs. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NexusLabs.Needlr.AgentFramework.Generators;

internal static class BootstrapCodeGenerator
{
    public static string GenerateBootstrapSource(string safeAssemblyName)
    {
        return $@"// <auto-generated/>
// Needlr AgentFramework Module Initializer
#nullable enable

using System.Runtime.CompilerServices;

namespace {safeAssemblyName}.Generated;

/// <summary>
/// Auto-registers source-generated Agent Framework types with the Needlr bootstrap.
/// Fires automatically when the assembly loads — no explicit <c>Add*FromGenerated()</c> calls needed.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""NexusLabs.Needlr.AgentFramework.Generators"", ""1.0.0"")]
internal static class NeedlrAgentFrameworkModuleInitializer
{{
    [ModuleInitializer]
    internal static void Initialize()
    {{
        global::NexusLabs.Needlr.AgentFramework.AgentFrameworkGeneratedBootstrap.Register(
            () => AgentFrameworkFunctionRegistry.AllFunctionTypes,
            () => AgentFrameworkFunctionGroupRegistry.AllGroups,
            () => AgentRegistry.AllAgentTypes,
            () => AgentHandoffTopologyRegistry.AllHandoffs,
            () => AgentGroupChatRegistry.AllGroups,
            () => AgentSequentialTopologyRegistry.AllPipelines);
        global::NexusLabs.Needlr.AgentFramework.AgentFrameworkGeneratedBootstrap.RegisterGraphTopology(
            () => AgentGraphTopologyRegistry.AllGraphs);
        global::NexusLabs.Needlr.AgentFramework.AgentFrameworkGeneratedBootstrap.RegisterAIFunctionProvider(
            new global::{safeAssemblyName}.Generated.GeneratedAIFunctionProvider());
    }}
}}
";
    }

    public static string GeneratePartialCompanionSource(
        NeedlrAiAgentTypeInfo agentType,
        Dictionary<string, List<string>> groupedByName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (agentType.NamespaceName is not null)
        {
            sb.AppendLine($"namespace {agentType.NamespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {agentType.ClassName}");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>The declared name of this agent, equal to the class name.</summary>");

        var toolsDocLines = BuildToolsDocComment(agentType, groupedByName);
        foreach (var line in toolsDocLines)
            sb.AppendLine(line);

        sb.AppendLine($"    public static string AgentName => nameof({agentType.ClassName});");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static List<string> BuildToolsDocComment(
        NeedlrAiAgentTypeInfo agentType,
        Dictionary<string, List<string>> groupedByName)
    {
        static string ShortName(string fqn)
        {
            var clean = fqn.StartsWith("global::") ? fqn.Substring(8) : fqn;
            var dot = clean.LastIndexOf('.');
            return dot >= 0 ? clean.Substring(dot + 1) : clean;
        }

        var lines = new List<string>();

        // FunctionTypes = new Type[0] — explicitly no tools
        if (agentType.HasExplicitFunctionTypes && agentType.ExplicitFunctionTypeFQNs.IsEmpty
            && agentType.FunctionGroupNames.IsEmpty)
        {
            lines.Add("    /// <remarks>This agent has no tools assigned (declared with an empty <c>FunctionTypes</c>).</remarks>");
            return lines;
        }

        // Neither set — uses all registered function types
        if (!agentType.HasExplicitFunctionTypes && agentType.FunctionGroupNames.IsEmpty)
        {
            lines.Add("    /// <remarks>This agent uses all registered function types.</remarks>");
            return lines;
        }

        // Build the resolved list of function types
        var entries = new List<(string displayName, string? groupSource)>();

        foreach (var group in agentType.FunctionGroupNames)
        {
            if (groupedByName.TryGetValue(group, out var types))
            {
                foreach (var typeFqn in types)
                    entries.Add((ShortName(typeFqn), group));
            }
            else
            {
                entries.Add(($"(unresolved group \"{group}\")", group));
            }
        }

        foreach (var typeFqn in agentType.ExplicitFunctionTypeFQNs)
        {
            var shortName = ShortName(typeFqn);
            if (!entries.Any(e => e.displayName == shortName))
                entries.Add((shortName, null));
        }

        lines.Add("    /// <remarks>");
        lines.Add("    /// <para>Agent tools:</para>");
        lines.Add("    /// <list type=\"bullet\">");
        foreach (var (displayName, groupSource) in entries)
        {
            var source = groupSource is not null ? $" (group <c>\"{groupSource}\"</c>)" : " (explicit type)";
            lines.Add($"    /// <item><term><see cref=\"{displayName}\"/>{source}</term></item>");
        }
        lines.Add("    /// </list>");
        lines.Add("    /// </remarks>");

        return lines;
    }
}
