// Copyright (c) NexusLabs. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NexusLabs.Needlr.AgentFramework.Generators;

internal static class ExtensionsCodeGenerator
{
    public static string GenerateWorkflowFactoryExtensionsSource(
        Dictionary<(string InitialAgentTypeName, string InitialAgentClassName), List<(string TargetAgentTypeName, string? HandoffReason)>> handoffByInitialAgent,
        Dictionary<string, List<string>> groupChatByGroupName,
        Dictionary<string, List<string>> sequenceByPipelineName,
        Dictionary<string, List<TerminationConditionEntry>> conditionsByAgentTypeName,
        string safeAssemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Needlr AgentFramework IWorkflowFactory Extension Methods");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Agents.AI.Workflows;");
        sb.AppendLine("using NexusLabs.Needlr.AgentFramework;");
        sb.AppendLine();
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated strongly-typed extension methods on <see cref=\"IWorkflowFactory\"/>.");
        sb.AppendLine("/// Each method encapsulates an agent type or group name so the composition root");
        sb.AppendLine("/// requires no direct agent type references or magic strings.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
        sb.AppendLine("public static partial class WorkflowFactoryExtensions");
        sb.AppendLine("{");

        foreach (var kvp in handoffByInitialAgent.OrderBy(k => k.Key.InitialAgentClassName))
        {
            var className = kvp.Key.InitialAgentClassName;
            var typeName = kvp.Key.InitialAgentTypeName;
            var methodName = $"Create{AgentDiscoveryHelper.StripAgentSuffix(className)}HandoffWorkflow";

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Creates a handoff workflow starting from <see cref=\"{typeName.Replace("global::", "")}\"/>.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    /// <remarks>");
            sb.AppendLine($"    /// Handoff targets declared via <see cref=\"global::NexusLabs.Needlr.AgentFramework.AgentHandoffsToAttribute\"/>:");
            sb.AppendLine($"    /// <list type=\"bullet\">");
            foreach (var (targetTypeName, reason) in kvp.Value)
            {
                var cref = targetTypeName.Replace("global::", "");
                if (string.IsNullOrEmpty(reason))
                    sb.AppendLine($"    /// <item><description><see cref=\"{cref}\"/></description></item>");
                else
                    sb.AppendLine($"    /// <item><description><see cref=\"{cref}\"/> — {reason}</description></item>");
            }
            sb.AppendLine($"    /// </list>");
            sb.AppendLine($"    /// </remarks>");
            sb.AppendLine($"    public static Workflow {methodName}(this IWorkflowFactory workflowFactory)");
            sb.AppendLine($"        => workflowFactory.CreateHandoffWorkflow<{typeName}>();");
            sb.AppendLine();

            var allHandoffAgents = new[] { typeName }
                .Concat(kvp.Value.Select(v => v.TargetAgentTypeName))
                .ToList();
            var handoffConditions = allHandoffAgents
                .SelectMany(t => conditionsByAgentTypeName.TryGetValue(t, out var c) ? c : Enumerable.Empty<TerminationConditionEntry>())
                .ToList();

            if (handoffConditions.Count > 0)
            {
                var runMethodName = $"Run{AgentDiscoveryHelper.StripAgentSuffix(className)}HandoffWorkflowAsync";
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// Creates and runs the handoff workflow starting from <see cref=\"{typeName.Replace("global::", "")}\"/>, applying declared termination conditions.");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    /// <remarks>");
                sb.AppendLine($"    /// Termination conditions are evaluated after each completed agent turn (Layer 2).");
                sb.AppendLine($"    /// The workflow stops early when any condition is satisfied.");
                sb.AppendLine($"    /// </remarks>");
                sb.AppendLine($"    /// <param name=\"workflowFactory\">The workflow factory.</param>");
                sb.AppendLine($"    /// <param name=\"message\">The input message to start the workflow.</param>");
                sb.AppendLine($"    /// <param name=\"cancellationToken\">Optional cancellation token.</param>");
                sb.AppendLine($"    /// <returns>A dictionary mapping executor IDs to their response text.</returns>");
                sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyDictionary<string, string>> {runMethodName}(");
                sb.AppendLine($"        this IWorkflowFactory workflowFactory,");
                sb.AppendLine($"        string message,");
                sb.AppendLine($"        global::System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        var workflow = workflowFactory.{methodName}();");
                sb.AppendLine($"        global::System.Collections.Generic.IReadOnlyList<global::NexusLabs.Needlr.AgentFramework.IWorkflowTerminationCondition> conditions =");
                sb.AppendLine($"            new global::System.Collections.Generic.List<global::NexusLabs.Needlr.AgentFramework.IWorkflowTerminationCondition>");
                sb.AppendLine($"            {{");
                foreach (var cond in handoffConditions)
                {
                    var args = cond.CtorArgLiterals.IsEmpty ? "" : string.Join(", ", cond.CtorArgLiterals);
                    sb.AppendLine($"                new {cond.ConditionTypeFQN}({args}),");
                }
                sb.AppendLine($"            }};");
                sb.AppendLine($"        return await global::NexusLabs.Needlr.AgentFramework.Workflows.StreamingRunWorkflowExtensions.RunAsync(workflow, message, conditions, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
        }

        foreach (var kvp in groupChatByGroupName.OrderBy(k => k.Key))
        {
            var groupName = kvp.Key;
            var methodSuffix = AgentDiscoveryHelper.GroupNameToPascalCase(groupName);
            var methodName = $"Create{methodSuffix}GroupChatWorkflow";
            var escapedGroupName = groupName.Replace("\"", "\\\"");

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Creates a round-robin group chat workflow for the \"{escapedGroupName}\" group.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    /// <remarks>");
            sb.AppendLine($"    /// Participants declared via <see cref=\"global::NexusLabs.Needlr.AgentFramework.AgentGroupChatMemberAttribute\"/>:");
            sb.AppendLine($"    /// <list type=\"bullet\">");
            foreach (var participantTypeName in kvp.Value)
            {
                var cref = participantTypeName.Replace("global::", "");
                sb.AppendLine($"    /// <item><description><see cref=\"{cref}\"/></description></item>");
            }
            sb.AppendLine($"    /// </list>");
            sb.AppendLine($"    /// </remarks>");
            sb.AppendLine($"    public static Workflow {methodName}(this IWorkflowFactory workflowFactory, int maxIterations = 10)");
            sb.AppendLine($"        => workflowFactory.CreateGroupChatWorkflow(\"{escapedGroupName}\", maxIterations);");
            sb.AppendLine();

            var gcConditions = kvp.Value
                .SelectMany(t => conditionsByAgentTypeName.TryGetValue(t, out var c) ? c : Enumerable.Empty<TerminationConditionEntry>())
                .ToList();

            if (gcConditions.Count > 0)
            {
                var runMethodName = $"Run{methodSuffix}GroupChatWorkflowAsync";
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// Creates and runs the \"{escapedGroupName}\" group chat workflow, applying declared termination conditions.");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    /// <remarks>");
                sb.AppendLine($"    /// Termination conditions are evaluated after each completed agent turn (Layer 2).");
                sb.AppendLine($"    /// The workflow stops early when any condition is satisfied.");
                sb.AppendLine($"    /// </remarks>");
                sb.AppendLine($"    /// <param name=\"workflowFactory\">The workflow factory.</param>");
                sb.AppendLine($"    /// <param name=\"message\">The input message to start the workflow.</param>");
                sb.AppendLine($"    /// <param name=\"maxIterations\">Maximum number of group chat iterations.</param>");
                sb.AppendLine($"    /// <param name=\"cancellationToken\">Optional cancellation token.</param>");
                sb.AppendLine($"    /// <returns>A dictionary mapping executor IDs to their response text.</returns>");
                sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyDictionary<string, string>> {runMethodName}(");
                sb.AppendLine($"        this IWorkflowFactory workflowFactory,");
                sb.AppendLine($"        string message,");
                sb.AppendLine($"        int maxIterations = 10,");
                sb.AppendLine($"        global::System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        var workflow = workflowFactory.{methodName}(maxIterations);");
                sb.AppendLine($"        global::System.Collections.Generic.IReadOnlyList<global::NexusLabs.Needlr.AgentFramework.IWorkflowTerminationCondition> conditions =");
                sb.AppendLine($"            new global::System.Collections.Generic.List<global::NexusLabs.Needlr.AgentFramework.IWorkflowTerminationCondition>");
                sb.AppendLine($"            {{");
                foreach (var cond in gcConditions)
                {
                    var args = cond.CtorArgLiterals.IsEmpty ? "" : string.Join(", ", cond.CtorArgLiterals);
                    sb.AppendLine($"                new {cond.ConditionTypeFQN}({args}),");
                }
                sb.AppendLine($"            }};");
                sb.AppendLine($"        return await global::NexusLabs.Needlr.AgentFramework.Workflows.StreamingRunWorkflowExtensions.RunAsync(workflow, message, conditions, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
        }

        foreach (var kvp in sequenceByPipelineName.OrderBy(k => k.Key))
        {
            var pipelineName = kvp.Key;
            var methodSuffix = AgentDiscoveryHelper.GroupNameToPascalCase(pipelineName);
            var methodName = $"Create{methodSuffix}SequentialWorkflow";
            var escapedPipelineName = pipelineName.Replace("\"", "\\\"");

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Creates a sequential pipeline workflow for the \"{escapedPipelineName}\" pipeline.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    /// <remarks>");
            sb.AppendLine($"    /// Agents declared via <see cref=\"global::NexusLabs.Needlr.AgentFramework.AgentSequenceMemberAttribute\"/> (in order):");
            sb.AppendLine($"    /// <list type=\"number\">");
            foreach (var memberTypeName in kvp.Value)
            {
                var cref = memberTypeName.Replace("global::", "");
                sb.AppendLine($"    /// <item><description><see cref=\"{cref}\"/></description></item>");
            }
            sb.AppendLine($"    /// </list>");
            sb.AppendLine($"    /// </remarks>");
            sb.AppendLine($"    public static Workflow {methodName}(this IWorkflowFactory workflowFactory)");
            sb.AppendLine($"        => workflowFactory.CreateSequentialWorkflow(\"{escapedPipelineName}\");");
            sb.AppendLine();

            var seqConditions = kvp.Value
                .SelectMany(t => conditionsByAgentTypeName.TryGetValue(t, out var c) ? c : Enumerable.Empty<TerminationConditionEntry>())
                .ToList();

            if (seqConditions.Count > 0)
            {
                var runMethodName = $"Run{methodSuffix}SequentialWorkflowAsync";
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// Creates and runs the \"{escapedPipelineName}\" sequential workflow, applying declared termination conditions.");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    /// <remarks>");
                sb.AppendLine($"    /// Termination conditions are evaluated after each completed agent turn (Layer 2).");
                sb.AppendLine($"    /// The workflow stops early when any condition is satisfied.");
                sb.AppendLine($"    /// </remarks>");
                sb.AppendLine($"    /// <param name=\"workflowFactory\">The workflow factory.</param>");
                sb.AppendLine($"    /// <param name=\"message\">The input message to start the workflow.</param>");
                sb.AppendLine($"    /// <param name=\"cancellationToken\">Optional cancellation token.</param>");
                sb.AppendLine($"    /// <returns>A dictionary mapping executor IDs to their response text.</returns>");
                sb.AppendLine($"    public static async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyDictionary<string, string>> {runMethodName}(");
                sb.AppendLine($"        this IWorkflowFactory workflowFactory,");
                sb.AppendLine($"        string message,");
                sb.AppendLine($"        global::System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        var workflow = workflowFactory.{methodName}();");
                sb.AppendLine($"        global::System.Collections.Generic.IReadOnlyList<global::NexusLabs.Needlr.AgentFramework.IWorkflowTerminationCondition> conditions =");
                sb.AppendLine($"            new global::System.Collections.Generic.List<global::NexusLabs.Needlr.AgentFramework.IWorkflowTerminationCondition>");
                sb.AppendLine($"            {{");
                foreach (var cond in seqConditions)
                {
                    var args = cond.CtorArgLiterals.IsEmpty ? "" : string.Join(", ", cond.CtorArgLiterals);
                    sb.AppendLine($"                new {cond.ConditionTypeFQN}({args}),");
                }
                sb.AppendLine($"            }};");
                sb.AppendLine($"        return await global::NexusLabs.Needlr.AgentFramework.Workflows.StreamingRunWorkflowExtensions.RunAsync(workflow, message, conditions, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateAgentFactoryExtensionsSource(
        List<NeedlrAiAgentTypeInfo> agents,
        Dictionary<string, ImmutableArray<string>> progressSinksByAgent,
        string safeAssemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Needlr AgentFramework IAgentFactory Extension Methods");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Agents.AI;");
        sb.AppendLine("using NexusLabs.Needlr.AgentFramework;");
        sb.AppendLine();
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated strongly-typed extension methods on <see cref=\"IAgentFactory\"/>.");
        sb.AppendLine("/// Each method creates an agent from its <c>[NeedlrAiAgent]</c> declaration,");
        sb.AppendLine("/// eliminating magic strings and direct type references at the composition root.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
        sb.AppendLine("public static class GeneratedAgentFactoryExtensions");
        sb.AppendLine("{");

        foreach (var agent in agents.OrderBy(a => a.ClassName))
        {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Creates an <see cref=\"AIAgent\"/> configured for <see cref=\"{agent.TypeName.Replace("global::", "")}\"/>.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static AIAgent Create{agent.ClassName}(this IAgentFactory factory)");
            sb.AppendLine($"        => factory.CreateAgent<{agent.TypeName}>();");
            sb.AppendLine();

            // If this agent has [ProgressSinks], emit a companion method
            if (progressSinksByAgent.TryGetValue(agent.ClassName, out var sinkFQNs) && sinkFQNs.Length > 0)
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// Returns the progress sink types declared via <c>[ProgressSinks]</c> on <see cref=\"{agent.TypeName.Replace("global::", "")}\"/>.");
                sb.AppendLine($"    /// Orchestrators use this to create reporters with the correct sinks for this agent.");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public static global::System.Type[] Get{agent.ClassName}ProgressSinkTypes()");
                sb.AppendLine("    {");
                sb.AppendLine("        return new global::System.Type[]");
                sb.AppendLine("        {");
                foreach (var sinkFQN in sinkFQNs)
                {
                    sb.AppendLine($"            typeof({sinkFQN}),");
                }
                sb.AppendLine("        };");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateAgentTopologyConstantsSource(
        List<NeedlrAiAgentTypeInfo> agents,
        List<AgentFunctionGroupEntry> groupEntries,
        Dictionary<string, List<string>> sequenceByPipelineName,
        string safeAssemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Needlr AgentFramework Topology Constants");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();

        sb.AppendLine("/// <summary>String constants for agent type names discovered at compile time.</summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
        sb.AppendLine("public static class AgentNames");
        sb.AppendLine("{");
        foreach (var agent in agents.OrderBy(a => a.ClassName))
        {
            sb.AppendLine($"    /// <summary>The name of <see cref=\"{agent.TypeName.Replace("global::", "")}\"/>.</summary>");
            sb.AppendLine($"    public const string {agent.ClassName} = \"{agent.ClassName}\";");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        var groupNames = groupEntries.Select(e => e.GroupName).Distinct().OrderBy(g => g).ToList();
        sb.AppendLine("/// <summary>String constants for function group names discovered at compile time.</summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
        sb.AppendLine("public static class GroupNames");
        sb.AppendLine("{");
        foreach (var gn in groupNames)
        {
            var propName = AgentDiscoveryHelper.GroupNameToPascalCase(gn);
            var escaped = gn.Replace("\"", "\\\"");
            sb.AppendLine($"    /// <summary>The group name <c>\"{escaped}\"</c>.</summary>");
            sb.AppendLine($"    public const string {propName} = \"{escaped}\";");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("/// <summary>String constants for sequential pipeline names discovered at compile time.</summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
        sb.AppendLine("public static class PipelineNames");
        sb.AppendLine("{");
        foreach (var pn in sequenceByPipelineName.Keys.OrderBy(k => k))
        {
            var propName = AgentDiscoveryHelper.GroupNameToPascalCase(pn);
            var escaped = pn.Replace("\"", "\\\"");
            sb.AppendLine($"    /// <summary>The pipeline name <c>\"{escaped}\"</c>.</summary>");
            sb.AppendLine($"    public const string {propName} = \"{escaped}\";");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string GenerateSyringeExtensionsSource(
        List<AgentFunctionGroupEntry> groupEntries,
        string safeAssemblyName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Needlr AgentFramework AgentFrameworkSyringe Extension Methods");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using NexusLabs.Needlr.AgentFramework;");
        sb.AppendLine();
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated strongly-typed extension methods on <see cref=\"AgentFrameworkSyringe\"/>.");
        sb.AppendLine("/// Each method registers a named function group without requiring direct type references.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"NexusLabs.Needlr.AgentFramework.Generators\", \"1.0.0\")]");
        sb.AppendLine("public static class GeneratedAgentFrameworkSyringeExtensions");
        sb.AppendLine("{");

        var byGroupName = groupEntries
            .GroupBy(e => e.GroupName)
            .OrderBy(g => g.Key);

        foreach (var grp in byGroupName)
        {
            var methodName = $"With{AgentDiscoveryHelper.GroupNameToPascalCase(grp.Key)}";
            var escapedGroupName = grp.Key.Replace("\"", "\\\"");
            var types = grp.Select(e => e.TypeName).Distinct().ToList();

            sb.AppendLine($"    /// <summary>Registers the '{escapedGroupName}' function group with the syringe.</summary>");
            sb.AppendLine($"    [RequiresUnreferencedCode(\"AgentFramework function setup uses reflection to discover [AgentFunction] methods.\")]");
            sb.AppendLine($"    [RequiresDynamicCode(\"AgentFramework function setup uses reflection APIs that require dynamic code generation.\")]");
            sb.AppendLine($"    public static AgentFrameworkSyringe {methodName}(this AgentFrameworkSyringe syringe)");
            sb.AppendLine($"        => syringe.AddAgentFunctions(new global::System.Type[] {{ {string.Join(", ", types.Select(t => $"typeof({t})"))} }});");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
