// Copyright (c) NexusLabs. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NexusLabs.Needlr.AgentFramework.Generators;

internal static class TopologyGraphCodeGenerator
{
    public static string GenerateTopologyGraphSource(
        string diagram,
        string safeAssemblyName)
    {
        var escaped = diagram.Replace("\"", "\"\"");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class AgentTopologyGraphDiagnostics");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string AgentTopologyGraph = @\"{escaped}\";");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateMermaidDiagram(
        Dictionary<(string InitialAgentTypeName, string InitialAgentClassName), List<(string TargetAgentTypeName, string? HandoffReason)>> handoffByInitialAgent,
        Dictionary<string, List<string>> groupChatByGroupName,
        Dictionary<string, List<string>> sequenceByPipelineName,
        Dictionary<string, GraphData>? graphDataByName = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("graph TD");

        foreach (var kvp in handoffByInitialAgent.OrderBy(k => k.Key.InitialAgentClassName))
        {
            var sourceClass = kvp.Key.InitialAgentClassName;
            foreach (var (targetFqn, reason) in kvp.Value)
            {
                var targetClass = AgentDiscoveryHelper.GetShortName(targetFqn);
                if (string.IsNullOrWhiteSpace(reason))
                    sb.AppendLine($"    {sourceClass} --> {targetClass}");
                else
                    sb.AppendLine($"    {sourceClass} -->|\"{EscapeMermaidLabel(reason!)}\"| {targetClass}");
            }
        }

        foreach (var kvp in groupChatByGroupName.OrderBy(k => k.Key))
        {
            sb.AppendLine($"    subgraph GroupChat_{SanitizeMermaidId(kvp.Key)}");
            foreach (var memberFqn in kvp.Value)
                sb.AppendLine($"        {AgentDiscoveryHelper.GetShortName(memberFqn)}");
            sb.AppendLine("    end");
        }

        foreach (var kvp in sequenceByPipelineName.OrderBy(k => k.Key))
        {
            sb.AppendLine($"    subgraph Sequential_{SanitizeMermaidId(kvp.Key)}");
            var agents = kvp.Value;
            if (agents.Count == 1)
            {
                sb.AppendLine($"        {AgentDiscoveryHelper.GetShortName(agents[0])}");
            }
            else
            {
                for (int i = 0; i < agents.Count - 1; i++)
                {
                    var cur = AgentDiscoveryHelper.GetShortName(agents[i]);
                    var next = AgentDiscoveryHelper.GetShortName(agents[i + 1]);
                    sb.AppendLine($"        {cur} -->|\"{i + 1}\"| {next}");
                }
            }
            sb.AppendLine("    end");
        }

        if (graphDataByName != null)
        {
            foreach (var kvp in graphDataByName.OrderBy(k => k.Key))
            {
                var graphName = kvp.Key;
                var graphData = kvp.Value;
                sb.AppendLine($"    subgraph Graph_{SanitizeMermaidId(graphName)}");

                foreach (var edge in graphData.Edges)
                {
                    var source = edge.SourceAgentClassName;
                    var target = AgentDiscoveryHelper.GetShortName(edge.TargetAgentTypeName);
                    if (string.IsNullOrWhiteSpace(edge.Condition))
                        sb.AppendLine($"        {source} --> {target}");
                    else
                        sb.AppendLine($"        {source} -->|\"{EscapeMermaidLabel(edge.Condition!)}\"| {target}");
                }

                sb.AppendLine("    end");
            }
        }

        return sb.ToString();
    }

    private static string SanitizeMermaidId(string name)
    {
        var sb = new StringBuilder();
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }

    private static string EscapeMermaidLabel(string label) =>
        label.Replace("\"", "&quot;");
}
