// Copyright (c) NexusLabs. All rights reserved.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NexusLabs.Needlr.AgentFramework.Generators;

internal static class TopologyGraphCodeGenerator
{
    public static string GenerateTopologyGraphSource(
        string diagram,
        string safeAssemblyName)
    {
        var escaped = diagram.Replace("\"", "\"\"");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class AgentTopologyGraphDiagnostics");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string AgentTopologyGraph = @\"{escaped}\";");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateMermaidDiagram(
        Dictionary<(string InitialAgentTypeName, string InitialAgentClassName), List<(string TargetAgentTypeName, string? HandoffReason)>> handoffByInitialAgent,
        Dictionary<string, List<string>> groupChatByGroupName,
        Dictionary<string, List<string>> sequenceByPipelineName,
        Dictionary<string, GraphData>? graphDataByName = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("graph TD");

        foreach (var kvp in handoffByInitialAgent.OrderBy(k => k.Key.InitialAgentClassName))
        {
            var sourceClass = kvp.Key.InitialAgentClassName;
            foreach (var (targetFqn, reason) in kvp.Value)
            {
                var targetClass = AgentDiscoveryHelper.GetShortName(targetFqn);
                if (string.IsNullOrWhiteSpace(reason))
                    sb.AppendLine($"    {sourceClass} --> {targetClass}");
                else
                    sb.AppendLine($"    {sourceClass} -->|\"{EscapeMermaidLabel(reason!)}\"| {targetClass}");
            }
        }

        foreach (var kvp in groupChatByGroupName.OrderBy(k => k.Key))
        {
            sb.AppendLine($"    subgraph GroupChat_{SanitizeMermaidId(kvp.Key)}");
            foreach (var memberFqn in kvp.Value)
                sb.AppendLine($"        {AgentDiscoveryHelper.GetShortName(memberFqn)}");
            sb.AppendLine("    end");
        }

        foreach (var kvp in sequenceByPipelineName.OrderBy(k => k.Key))
        {
            sb.AppendLine($"    subgraph Sequential_{SanitizeMermaidId(kvp.Key)}");
            var agents = kvp.Value;
            if (agents.Count == 1)
            {
                sb.AppendLine($"        {AgentDiscoveryHelper.GetShortName(agents[0])}");
            }
            else
            {
                for (int i = 0; i < agents.Count - 1; i++)
                {
                    var cur = AgentDiscoveryHelper.GetShortName(agents[i]);
                    var next = AgentDiscoveryHelper.GetShortName(agents[i + 1]);
                    sb.AppendLine($"        {cur} -->|\"{i + 1}\"| {next}");
                }
            }
            sb.AppendLine("    end");
        }

        if (graphDataByName != null)
        {
            foreach (var kvp in graphDataByName.OrderBy(k => k.Key))
            {
                var graphName = kvp.Key;
                var graphData = kvp.Value;
                sb.AppendLine($"    subgraph Graph_{SanitizeMermaidId(graphName)}");

                // Collect entry point class names for stadium shape rendering
                var entryPointClassNames = new HashSet<string>();
                foreach (var ep in graphData.EntryPoints)
                    entryPointClassNames.Add(ep.AgentClassName);

                // Collect reducer class names for hexagon shape rendering
                var reducerClassNames = new HashSet<string>();
                foreach (var r in graphData.Reducers)
                    reducerClassNames.Add(r.AgentClassName);

                // Collect node join modes for labeling
                var joinModeByClassName = new Dictionary<string, int>();
                foreach (var node in graphData.Nodes)
                {
                    if (node.JoinMode != 0)
                        joinModeByClassName[node.AgentClassName] = node.JoinMode;
                }

                // Emit entry point node declarations with stadium shape
                foreach (var epClassName in entryPointClassNames)
                    sb.AppendLine($"        {epClassName}([{epClassName}])");

                // Emit reducer node declarations with hexagon shape
                foreach (var reducerClassName in reducerClassNames)
                {
                    if (!entryPointClassNames.Contains(reducerClassName))
                        sb.AppendLine($"        {reducerClassName}{{{{{reducerClassName}}}}}");
                }

                foreach (var edge in graphData.Edges)
                {
                    var source = edge.SourceAgentClassName;
                    var target = AgentDiscoveryHelper.GetShortName(edge.TargetAgentTypeName);

                    var arrow = edge.IsRequired ? "-->" : "-.->";

                    // Build label parts
                    string? label = null;
                    if (!string.IsNullOrWhiteSpace(edge.Condition))
                        label = EscapeMermaidLabel(edge.Condition!);

                    // Add JoinMode annotation on edges targeting nodes with non-default join mode
                    if (joinModeByClassName.TryGetValue(target, out var joinMode))
                    {
                        var joinLabel = joinMode == 1 ? "WaitAny" : $"JoinMode{joinMode}";
                        label = label != null ? $"{label}, {joinLabel}" : joinLabel;
                    }

                    if (label != null)
                        sb.AppendLine($"        {source} {arrow}|\"{label}\"| {target}");
                    else
                        sb.AppendLine($"        {source} {arrow} {target}");
                }

                sb.AppendLine("    end");
            }
        }

        return sb.ToString();
    }

    private static string SanitizeMermaidId(string name)
    {
        var sb = new StringBuilder();
        foreach (var c in name)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }

    private static string EscapeMermaidLabel(string label) =>
        label.Replace("\"", "&quot;");
}
