using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using NexusLabs.Needlr.Logging.Generators.Models;

namespace NexusLabs.Needlr.Logging.Generators.CodeGen;

/// <summary>
/// Emits the implementation of <c>[NeedlrLoggerMessage]</c> partial methods. The generated body reuses
/// the public <c>LoggerMessage.Define</c> fast path and wraps it with the cancellation guard.
/// </summary>
internal static class NeedlrLoggerMessageCodeGenerator
{
    private const int MaxDefineParameters = 6;

    private const string LoggerMessage = "global::Microsoft.Extensions.Logging.LoggerMessage";
    private const string LoggerExtensions = "global::Microsoft.Extensions.Logging.LoggerExtensions";
    private const string LogLevelType = "global::Microsoft.Extensions.Logging.LogLevel";
    private const string EventIdType = "global::Microsoft.Extensions.Logging.EventId";
    private const string LogDefineOptionsType = "global::Microsoft.Extensions.Logging.LogDefineOptions";
    private const string ILoggerType = "global::Microsoft.Extensions.Logging.ILogger";
    private const string ActionType = "global::System.Action";
    private const string NullableExceptionType = "global::System.Exception?";
    private const string PolicyType = "global::NexusLabs.Needlr.Logging.NeedlrCancellationLogging";
    private const string BehaviorType = "global::NexusLabs.Needlr.Logging.CancellationLoggingBehavior";

    /// <summary>
    /// Generates a source file holding the generated members for every logging method that shares a
    /// containing type.
    /// </summary>
    /// <param name="namespaceName">The containing namespace, or an empty string for the global namespace.</param>
    /// <param name="containingTypes">The chain of partial containing types, outermost first.</param>
    /// <param name="methods">The methods to emit, paired with a unique callback field name.</param>
    /// <returns>The generated C# source text.</returns>
    public static string GenerateForType(
        string namespaceName,
        ImmutableArray<ContainingTypeInfo> containingTypes,
        IReadOnlyList<(DiscoveredLogMethod Method, string FieldName)> methods)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var indent = 0;
        var hasNamespace = !string.IsNullOrEmpty(namespaceName);
        if (hasNamespace)
        {
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            indent++;
        }

        foreach (var type in containingTypes)
        {
            AppendLine(builder, indent, $"partial {type.Keyword} {type.Name}{type.TypeParameterList}");
            AppendLine(builder, indent, "{");
            indent++;
        }

        var firstMethod = true;
        foreach (var (method, fieldName) in methods)
        {
            if (!firstMethod)
            {
                builder.AppendLine();
            }

            firstMethod = false;
            EmitMethod(builder, indent, method, fieldName);
        }

        for (var i = 0; i < containingTypes.Length; i++)
        {
            indent--;
            AppendLine(builder, indent, "}");
        }

        if (hasNamespace)
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void EmitMethod(StringBuilder builder, int indent, DiscoveredLogMethod method, string fieldName)
    {
        var messageParameters = method.Parameters
            .Where(parameter => parameter.Role == ParameterRole.Message)
            .ToList();

        LogParameterInfo? exception = null;
        foreach (var parameter in method.Parameters)
        {
            if (parameter.Role == ParameterRole.Exception)
            {
                exception = parameter;
                break;
            }
        }

        var useDefine = messageParameters.Count <= MaxDefineParameters;
        var levelExpression = $"{LogLevelType}.{method.LevelName}";
        var eventIdExpression = $"new {EventIdType}({method.EventId}, {Literal(method.EventName)})";
        var messageLiteral = Literal(method.Message);
        var messageArgumentsTrailing = messageParameters.Count > 0
            ? ", " + string.Join(", ", messageParameters.Select(parameter => parameter.Name))
            : string.Empty;

        if (useDefine)
        {
            EmitCallbackField(builder, indent, method, fieldName, messageParameters, levelExpression, eventIdExpression, messageLiteral);
            builder.AppendLine();
        }

        var signature = string.Join(", ", method.Parameters.Select(parameter => $"{parameter.Type} {parameter.Name}"));
        var modifiersPrefix = string.IsNullOrEmpty(method.Modifiers) ? string.Empty : method.Modifiers + " ";
        AppendLine(builder, indent, $"{modifiersPrefix}partial void {method.MethodName}({signature})");
        AppendLine(builder, indent, "{");

        if (exception.HasValue)
        {
            EmitCancellationGuard(builder, indent + 1, method, exception.Value.Name, eventIdExpression, messageLiteral, messageArgumentsTrailing);
        }

        if (useDefine)
        {
            var exceptionArgument = exception.HasValue ? exception.Value.Name : "null";
            var callArguments = $"{method.LoggerAccess}{messageArgumentsTrailing}, {exceptionArgument}";

            if (method.SkipEnabledCheck)
            {
                AppendLine(builder, indent + 1, $"{fieldName}({callArguments});");
            }
            else
            {
                AppendLine(builder, indent + 1, $"if ({method.LoggerAccess}.IsEnabled({levelExpression}))");
                AppendLine(builder, indent + 1, "{");
                AppendLine(builder, indent + 2, $"{fieldName}({callArguments});");
                AppendLine(builder, indent + 1, "}");
            }
        }
        else
        {
            EmitLogCall(builder, indent + 1, method, levelExpression, eventIdExpression, messageLiteral, messageArgumentsTrailing, exception);
        }

        AppendLine(builder, indent, "}");
    }

    private static void EmitCallbackField(
        StringBuilder builder,
        int indent,
        DiscoveredLogMethod method,
        string fieldName,
        IReadOnlyList<LogParameterInfo> messageParameters,
        string levelExpression,
        string eventIdExpression,
        string messageLiteral)
    {
        var actionTypeArguments = new StringBuilder(ILoggerType);
        foreach (var parameter in messageParameters)
        {
            actionTypeArguments.Append(", ").Append(parameter.Type);
        }

        actionTypeArguments.Append(", ").Append(NullableExceptionType);

        var defineGenericArguments = messageParameters.Count > 0
            ? "<" + string.Join(", ", messageParameters.Select(parameter => parameter.Type)) + ">"
            : string.Empty;

        var skipEnabledCheck = method.SkipEnabledCheck ? "true" : "false";

        AppendLine(builder, indent, $"private static readonly {ActionType}<{actionTypeArguments}> {fieldName} =");
        AppendLine(builder, indent + 1, $"{LoggerMessage}.Define{defineGenericArguments}(");
        AppendLine(builder, indent + 2, $"{levelExpression},");
        AppendLine(builder, indent + 2, $"{eventIdExpression},");
        AppendLine(builder, indent + 2, $"{messageLiteral},");
        AppendLine(builder, indent + 2, $"new {LogDefineOptionsType}() {{ SkipEnabledCheck = {skipEnabledCheck} }});");
    }

    private static void EmitCancellationGuard(
        StringBuilder builder,
        int indent,
        DiscoveredLogMethod method,
        string exceptionName,
        string eventIdExpression,
        string messageLiteral,
        string messageArgumentsTrailing)
    {
        AppendLine(builder, indent, $"if ({exceptionName} is not null && {PolicyType}.IsCancellation({exceptionName}))");
        AppendLine(builder, indent, "{");
        AppendLine(builder, indent + 1, $"switch ({PolicyType}.Behavior)");
        AppendLine(builder, indent + 1, "{");
        AppendLine(builder, indent + 2, $"case {BehaviorType}.Skip:");
        AppendLine(builder, indent + 3, "return;");
        AppendLine(builder, indent + 2, $"case {BehaviorType}.Demote:");
        AppendLine(builder, indent + 3, $"{LoggerExtensions}.Log(");
        AppendLine(builder, indent + 4, $"{method.LoggerAccess},");
        AppendLine(builder, indent + 4, $"{PolicyType}.DemotedLevel,");
        AppendLine(builder, indent + 4, $"{eventIdExpression},");
        AppendLine(builder, indent + 4, $"{exceptionName},");
        AppendLine(builder, indent + 4, $"{messageLiteral}{messageArgumentsTrailing});");
        AppendLine(builder, indent + 3, "return;");
        AppendLine(builder, indent + 1, "}");
        AppendLine(builder, indent, "}");
    }

    private static void EmitLogCall(
        StringBuilder builder,
        int indent,
        DiscoveredLogMethod method,
        string levelExpression,
        string eventIdExpression,
        string messageLiteral,
        string messageArgumentsTrailing,
        LogParameterInfo? exception)
    {
        AppendLine(builder, indent, $"{LoggerExtensions}.Log(");
        AppendLine(builder, indent + 1, $"{method.LoggerAccess},");
        AppendLine(builder, indent + 1, $"{levelExpression},");
        AppendLine(builder, indent + 1, $"{eventIdExpression},");
        if (exception.HasValue)
        {
            AppendLine(builder, indent + 1, $"{exception.Value.Name},");
        }

        AppendLine(builder, indent + 1, $"{messageLiteral}{messageArgumentsTrailing});");
    }

    private static string Literal(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                case '\0':
                    builder.Append("\\0");
                    break;
                default:
                    builder.Append(character);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static void AppendLine(StringBuilder builder, int indent, string text)
    {
        if (indent > 0)
        {
            builder.Append(new string(' ', indent * 4));
        }

        builder.AppendLine(text);
    }
}
