using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using NexusLabs.Needlr.Avalonia.Diagnostics;

namespace NexusLabs.Needlr.Avalonia;

/// <summary>
/// Source generator that emits design-time parameterless constructors for Avalonia
/// controls decorated with <c>[GenerateAvaloniaDesignTimeConstructor]</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class AvaloniaDesignTimeConstructorGenerator : IIncrementalGenerator
{
    private const string AttributeFullName =
        "NexusLabs.Needlr.Avalonia.GenerateAvaloniaDesignTimeConstructorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => GetClassInfo(ctx));

        context.RegisterSourceOutput(candidates, static (spc, info) =>
        {
            if (info == null)
                return;

            var classInfo = info.Value;

            // Validate: must be partial
            if (!classInfo.IsPartial)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    AvaloniaDiagnosticDescriptors.ClassMustBePartial,
                    classInfo.Location,
                    classInfo.ClassName));
                return;
            }

            // Validate: must not already have a parameterless constructor
            if (classInfo.HasParameterlessCtor)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    AvaloniaDiagnosticDescriptors.AlreadyHasParameterlessCtor,
                    classInfo.Location,
                    classInfo.ClassName));
                return;
            }

            // Warn: should have at least one constructor with parameters
            if (!classInfo.HasParameterizedCtor)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    AvaloniaDiagnosticDescriptors.NoParameterizedCtor,
                    classInfo.Location,
                    classInfo.ClassName));
                return;
            }

            // Emit the design-time constructor
            var source = GenerateSource(classInfo);
            spc.AddSource(
                $"{classInfo.ClassName}.DesignTimeCtor.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static DesignTimeCtorClassInfo? GetClassInfo(
        GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var classDecl = ctx.TargetNode as ClassDeclarationSyntax;
        var isPartial = classDecl?.Modifiers.Any(SyntaxKind.PartialKeyword) ?? false;

        var hasParameterlessCtor = typeSymbol.InstanceConstructors
            .Any(c => !c.IsStatic &&
                      c.DeclaredAccessibility == Accessibility.Public &&
                      c.Parameters.Length == 0 &&
                      !c.IsImplicitlyDeclared);

        var hasParameterizedCtor = typeSymbol.InstanceConstructors
            .Any(c => !c.IsStatic &&
                      c.DeclaredAccessibility == Accessibility.Public &&
                      c.Parameters.Length > 0);

        var namespaceName = typeSymbol.ContainingNamespace?.IsGlobalNamespace == true
            ? null
            : typeSymbol.ContainingNamespace?.ToDisplayString();

        // Build the class declaration modifiers (sealed, internal, etc.)
        var modifiers = "";
        if (classDecl != null)
        {
            var mods = classDecl.Modifiers
                .Where(m => m.IsKind(SyntaxKind.SealedKeyword) ||
                            m.IsKind(SyntaxKind.InternalKeyword) ||
                            m.IsKind(SyntaxKind.PublicKeyword))
                .Select(m => m.Text);
            modifiers = string.Join(" ", mods);
        }

        return new DesignTimeCtorClassInfo(
            className: typeSymbol.Name,
            namespaceName: namespaceName,
            modifiers: modifiers,
            isPartial: isPartial,
            hasParameterlessCtor: hasParameterlessCtor,
            hasParameterizedCtor: hasParameterizedCtor,
            location: ctx.TargetNode.GetLocation());
    }

    private static string GenerateSource(DesignTimeCtorClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor.");
        sb.AppendLine();

        if (info.NamespaceName != null)
        {
            sb.AppendLine($"namespace {info.NamespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {info.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Design-time constructor for Avalonia's XAML previewer.");
        sb.AppendLine("    /// At runtime, the DI container uses the richer constructor.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public {info.ClassName}()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!global::Avalonia.Controls.Design.IsDesignMode)");
        sb.AppendLine("        {");
        sb.AppendLine($"            throw new global::System.InvalidOperationException(");
        sb.AppendLine($"                \"The parameterless constructor on '{info.ClassName}' exists only for \" +");
        sb.AppendLine($"                \"Avalonia design-time support. At runtime, resolve this type from \" +");
        sb.AppendLine($"                \"the DI container to use the constructor with dependencies.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        InitializeComponent();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#pragma warning restore CS8618");

        return sb.ToString();
    }

    private readonly struct DesignTimeCtorClassInfo
    {
        public DesignTimeCtorClassInfo(
            string className,
            string? namespaceName,
            string modifiers,
            bool isPartial,
            bool hasParameterlessCtor,
            bool hasParameterizedCtor,
            Location location)
        {
            ClassName = className;
            NamespaceName = namespaceName;
            Modifiers = modifiers;
            IsPartial = isPartial;
            HasParameterlessCtor = hasParameterlessCtor;
            HasParameterizedCtor = hasParameterizedCtor;
            Location = location;
        }

        public string ClassName { get; }
        public string? NamespaceName { get; }
        public string Modifiers { get; }
        public bool IsPartial { get; }
        public bool HasParameterlessCtor { get; }
        public bool HasParameterizedCtor { get; }
        public Location Location { get; }
    }
}
