using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Logging;

using NexusLabs.Needlr.AspNet;

namespace NexusLabs.Needlr.SignalR;

/// <summary>
/// Marker interface for source-generated SignalR hub registration.
/// </summary>
/// <remarks>
/// When using source generation, the generator emits a 
/// <c>SignalRHubRegistrations.MapGeneratedHubs(WebApplication)</c> extension method
/// that can be called directly in your Program.cs:
/// <code>
/// var app = builder.Build();
/// app.MapGeneratedHubs(); // Generated at compile-time
/// </code>
/// 
/// This approach is preferred for AOT/trimmed applications because it avoids
/// all runtime reflection. The <see cref="SignalRHubRegistrationPlugin"/> uses
/// reflection and is marked with appropriate AOT warnings.
/// 
/// To enable hub registration generation, implement <see cref="IHubRegistrationPlugin"/>
/// with compile-time constant property values:
/// <code>
/// public class ChatHubPlugin : IHubRegistrationPlugin
/// {
///     public string HubPath => "/chat";
///     public Type HubType => typeof(ChatHub);
/// }
/// </code>
/// </remarks>
public static class GeneratedSignalRHubRegistration
{
    /// <summary>
    /// Extension method placeholder that provides documentation for source-generated hub registration.
    /// The actual implementation is generated by NexusLabs.Needlr.Generators when 
    /// IHubRegistrationPlugin implementations are discovered.
    /// </summary>
    /// <remarks>
    /// This method exists to provide IntelliSense documentation. The generated
    /// <c>NexusLabs.Needlr.Generated.SignalRHubRegistrations.MapGeneratedHubs()</c>
    /// extension method should be called instead.
    /// </remarks>
    public static void DocumentationPlaceholder()
    {
        // This method is intentionally empty.
        // It exists only for documentation purposes.
        // The actual MapGeneratedHubs() method is source-generated.
    }
}

