namespace NexusLabs.Needlr.AgentFramework.Diagnostics;

/// <summary>
/// Token usage breakdown for a single LLM call or aggregate across an agent run.
/// </summary>
/// <remarks>
/// <para>
/// Each <see cref="ChatCompletionDiagnostics"/> carries a <see cref="TokenUsage"/> for
/// that individual call. <see cref="IAgentRunDiagnostics.AggregateTokenUsage"/> sums
/// across all calls in one agent run. <see cref="IPipelineRunResult.AggregateTokenUsage"/>
/// sums across all stages in a pipeline.
/// </para>
/// <para>
/// Token counts come from the LLM provider's response metadata. If the provider does
/// not report a field, the corresponding value is <c>0</c>.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var diagnostics = accessor.LastRunDiagnostics;
/// var usage = diagnostics.AggregateTokenUsage;
/// Console.WriteLine($"Input: {usage.InputTokens} (cached: {usage.CachedInputTokens})");
/// Console.WriteLine($"Output: {usage.OutputTokens} (reasoning: {usage.ReasoningTokens})");
/// Console.WriteLine($"Total: {usage.TotalTokens}");
/// </code>
/// </example>
/// <param name="InputTokens">Number of tokens in the prompt sent to the model.</param>
/// <param name="OutputTokens">Number of tokens generated by the model.</param>
/// <param name="TotalTokens">Sum of input and output tokens (may include overhead tokens not in either count).</param>
/// <param name="CachedInputTokens">Subset of <paramref name="InputTokens"/> served from the provider's prompt cache. Cached tokens are typically billed at a reduced rate.</param>
/// <param name="ReasoningTokens">Tokens consumed by chain-of-thought reasoning (e.g., OpenAI o-series models). Zero for models that do not report reasoning tokens.</param>
public sealed record TokenUsage(
    long InputTokens,
    long OutputTokens,
    long TotalTokens,
    long CachedInputTokens,
    long ReasoningTokens);
