namespace NexusLabs.Needlr;

/// <summary>
/// Specifies constructor parameter types for a partial class whose constructor
/// will be generated by another source generator.
/// </summary>
/// <remarks>
/// <para>
/// Use this attribute when your partial class receives a constructor from another
/// source generator (e.g., a code generator that adds a primary constructor based
/// on an attribute). Since Needlr's source generator cannot see constructors added
/// by other generators, you must explicitly declare the expected constructor
/// parameter types.
/// </para>
/// <para>
/// Needlr will generate a factory that calls the constructor with the specified
/// parameter types, resolving each dependency from the service provider.
/// </para>
/// <para>
/// If the declared parameter types don't match the actual generated constructor,
/// the build will fail with a compile error.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // Your partial class - another generator will add a primary constructor
/// [DeferToContainer(typeof(IRepository), typeof(ILogger&lt;MyService&gt;))]
/// [GeneratedService]  // This triggers another source generator
/// public partial class MyService { }
/// 
/// // The other generator produces:
/// // public partial class MyService(IRepository repository, ILogger&lt;MyService&gt; logger) { }
/// 
/// // Needlr generates factory based on your [DeferToContainer] declaration:
/// // sp => new MyService(
/// //     sp.GetRequiredService&lt;IRepository&gt;(),
/// //     sp.GetRequiredService&lt;ILogger&lt;MyService&gt;&gt;())
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class DeferToContainerAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of <see cref="DeferToContainerAttribute"/>
    /// with the specified constructor parameter types.
    /// </summary>
    /// <param name="constructorParameterTypes">
    /// The types of the constructor parameters in order. Each type will be
    /// resolved from the service provider when creating an instance.
    /// </param>
    public DeferToContainerAttribute(params Type[] constructorParameterTypes)
    {
        ConstructorParameterTypes = constructorParameterTypes ?? Array.Empty<Type>();
    }

    /// <summary>
    /// Gets the constructor parameter types in order.
    /// </summary>
    /// <remarks>
    /// These types are used by the source generator to create a factory delegate
    /// that resolves each parameter from the service provider and passes them
    /// to the constructor.
    /// </remarks>
    public Type[] ConstructorParameterTypes { get; }
}
