namespace NexusLabs.Needlr.Catalog;

/// <summary>
/// Provides compile-time service registration metadata.
/// Generated by Needlr source generator when [GenerateTypeRegistry] is used.
/// </summary>
public interface IServiceCatalog
{
    /// <summary>
    /// Gets the assembly name this catalog was generated for.
    /// </summary>
    string AssemblyName { get; }

    /// <summary>
    /// Gets all discovered service registrations.
    /// </summary>
    IReadOnlyList<ServiceCatalogEntry> Services { get; }

    /// <summary>
    /// Gets all discovered decorator registrations.
    /// </summary>
    IReadOnlyList<DecoratorCatalogEntry> Decorators { get; }

    /// <summary>
    /// Gets all discovered hosted service registrations.
    /// </summary>
    IReadOnlyList<HostedServiceCatalogEntry> HostedServices { get; }

    /// <summary>
    /// Gets all discovered intercepted service registrations.
    /// </summary>
    IReadOnlyList<InterceptedServiceCatalogEntry> InterceptedServices { get; }

    /// <summary>
    /// Gets all discovered options/configuration bindings.
    /// </summary>
    IReadOnlyList<OptionsCatalogEntry> Options { get; }

    /// <summary>
    /// Gets all discovered plugin registrations.
    /// </summary>
    IReadOnlyList<PluginCatalogEntry> Plugins { get; }
}
